/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.spring.io/snapshot")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation ("VinoDomain:VinoDomain:0.0.1-SNAPSHOT")
    api("org.apache.commons:commons-lang3:3.12.0")
    api("org.springframework:spring-context:6.0.9")
    api("javax.persistence:javax.persistence-api:2.2")
    api("org.slf4j:slf4j-api:2.0.5")
    api("org.slf4j:slf4j-nop:2.0.5")
    api("org.hibernate:hibernate-core:6.1.7.Final")
    api("org.springframework:spring-orm:6.0.6")
    api("junit:junit:4.13.2")
}

group = "VinoDao"
version = "0.0.1-SNAPSHOT"
description = "Vino Dao"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
