/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
}

repositories {
    mavenCentral()
}

dependencies {
    api("org.apache.commons:commons-lang3:3.20.0")
}

group = "VinoDomain"
version = "1.0.0"
description = "VinoDomain"
java.sourceCompatibility = JavaVersion.VERSION_17
