-- Wine auction price data — normalized relational schema.
-- Matches the VinoDomain model: Provider, Unit, Wine, Offering, WineOffering.

CREATE TABLE provider (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE unit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deciliters NUMERIC(5, 2) NOT NULL UNIQUE,
    name VARCHAR(255)
);

CREATE TABLE wine (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(1000) NOT NULL,
    producer VARCHAR(255),
    vintage INTEGER,
    region VARCHAR(255),
    origin VARCHAR(255)
);

CREATE TABLE offering (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT NOT NULL REFERENCES provider (id),
    provider_offering_id VARCHAR(100),
    event_identifier VARCHAR(255),
    offering_date DATE,
    price_min NUMERIC(12, 2),
    price_max NUMERIC(12, 2),
    realized_price NUMERIC(12, 2),
    is_ohk BOOLEAN DEFAULT FALSE,
    note TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE wine_offering (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wine_id BIGINT NOT NULL REFERENCES wine (id),
    offering_id BIGINT NOT NULL REFERENCES offering (id),
    unit_id BIGINT NOT NULL REFERENCES unit (id),
    no_of_bottles INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_wine_name ON wine (name);
CREATE INDEX idx_offering_provider ON offering (provider_id);
CREATE INDEX idx_offering_date ON offering (offering_date);
CREATE INDEX idx_wineoffering_wine ON wine_offering (wine_id);
CREATE INDEX idx_wineoffering_offering ON wine_offering (offering_id);
