function serendipity(){var P='',wb='" for "gwt:onLoadErrorFn"',ub='" for "gwt:onPropertyErrorFn"',ib='"><\/script>',Z='#',Eb='&',uc='../charts/amcharts/flash/swfobject.js',vc='../charts/amcharts/flash/swfobject.js"><\/script>',sc='../charts/fusioncharts/javascript/FusionCharts.js',tc='../charts/fusioncharts/javascript/FusionCharts.js"><\/script>',Rb='.cache.html',_='/',Mb='62D053CE4B682FDDB149205416DB8FDB',Ob='81CAF7D1161A85576CC58068983B2E41',Qb=':',ob='::',yc='<script defer="defer">serendipity.onInjectionDone(\'serendipity\')<\/script>',hb='<script id="',$b='<script language="javascript" src="',rb='=',$='?',tb='Bad handler "',Yb='DOMContentLoaded',Pb='E580B8D0402D51E826EA98541E9C8AE5',jb='SCRIPT',Hb='Unexpected exception in locale detection, using default: ',Gb='_',Fb='__gwt_Locale',gb='__gwt_marker_serendipity',kb='base',cb='baseUrl',T='begin',S='bootstrap',bb='clear.cache.gif',qb='content',Lb='de',Cb='default',Nb='en',Y='end',U='gwt.codesvr=',V='gwt.hosted=',W='gwt.hybrid',Sb='gwt/standard/standard.css',vb='gwt:onLoadErrorFn',sb='gwt:onPropertyErrorFn',pb='gwt:property',Xb='head',Jb='hosted.html?serendipity',Wb='href',xb='iframe',ab='img',yb="javascript:''",Tb='link',Ib='loadExternalRefs',Bb='locale',Db='locale=',lb='meta',Ab='moduleRequested',X='moduleStartup',mb='name',zb='position:absolute;width:0;height:0;border:none',Ub='rel',kc='sc/modules/ISC_Calendar.js',lc='sc/modules/ISC_Calendar.js"><\/script>',cc='sc/modules/ISC_Containers.js',dc='sc/modules/ISC_Containers.js"><\/script>',Zb='sc/modules/ISC_Core.js',_b='sc/modules/ISC_Core.js"><\/script>',mc='sc/modules/ISC_DataBinding.js',nc='sc/modules/ISC_DataBinding.js"><\/script>',gc='sc/modules/ISC_Forms.js',hc='sc/modules/ISC_Forms.js"><\/script>',ac='sc/modules/ISC_Foundation.js',bc='sc/modules/ISC_Foundation.js"><\/script>',ec='sc/modules/ISC_Grids.js',fc='sc/modules/ISC_Grids.js"><\/script>',qc='sc/modules/ISC_PluginBridges.js',rc='sc/modules/ISC_PluginBridges.js"><\/script>',ic='sc/modules/ISC_RichTextEditor.js',jc='sc/modules/ISC_RichTextEditor.js"><\/script>',oc='sc/skins/Enterprise/load_skin.js',pc='sc/skins/Enterprise/load_skin.js"><\/script>',wc='sc/skins/EnterpriseBlue/load_skin.js',xc='sc/skins/EnterpriseBlue/load_skin.js"><\/script>',db='script',Kb='selectingPermutation',Q='serendipity',eb='serendipity.nocache.js',nb='serendipity::',R='startup',Vb='stylesheet',fb='undefined';var l=window,m=document,n=l.__gwtStatsEvent?function(a){return l.__gwtStatsEvent(a)}:null,o=l.__gwtStatsSessionId?l.__gwtStatsSessionId:null,p,q,r,s=P,t={},u=[],v=[],w=[],x=0,y,z;n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:T});if(!l.__gwt_stylesLoaded){l.__gwt_stylesLoaded={}}if(!l.__gwt_scriptsLoaded){l.__gwt_scriptsLoaded={}}function A(){var b=false;try{var c=l.location.search;return (c.indexOf(U)!=-1||(c.indexOf(V)!=-1||l.external&&l.external.gwtOnLoad))&&c.indexOf(W)==-1}catch(a){}A=function(){return b};return b}
function B(){if(p&&q){var b=m.getElementById(Q);var c=b.contentWindow;if(A()){c.__gwt_getProperty=function(a){return H(a)}}serendipity=null;c.gwtOnLoad(y,Q,s,x);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Y})}}
function C(){function e(a){var b=a.lastIndexOf(Z);if(b==-1){b=a.length}var c=a.indexOf($);if(c==-1){c=a.length}var d=a.lastIndexOf(_,Math.min(c,b));return d>=0?a.substring(0,d+1):P}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=m.createElement(ab);b.src=a+bb;a=e(b.src)}return a}
function g(){var a=F(cb);if(a!=null){return a}return P}
function h(){var a=m.getElementsByTagName(db);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(eb)!=-1){return e(a[b].src)}}return P}
function i(){var a;if(typeof isBodyLoaded==fb||!isBodyLoaded()){var b=gb;var c;m.write(hb+b+ib);c=m.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=jb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return P}
function j(){var a=m.getElementsByTagName(kb);if(a.length>0){return a[a.length-1].href}return P}
var k=g();if(k==P){k=h()}if(k==P){k=i()}if(k==P){k=j()}if(k==P){k=e(m.location.href)}k=f(k);s=k;return k}
function D(){var b=document.getElementsByTagName(lb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(mb),g;if(f){f=f.replace(nb,P);if(f.indexOf(ob)>=0){continue}if(f==pb){g=e.getAttribute(qb);if(g){var h,i=g.indexOf(rb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=P}t[f]=h}}else if(f==sb){g=e.getAttribute(qb);if(g){try{z=eval(g)}catch(a){alert(tb+g+ub)}}}else if(f==vb){g=e.getAttribute(qb);if(g){try{y=eval(g)}catch(a){alert(tb+g+wb)}}}}}}
function E(a,b){return b in u[a]}
function F(a){var b=t[a];return b==null?null:b}
function G(a,b){var c=w;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function H(a){var b=v[a](),c=u[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(z){z(a,d,b)}throw null}
var I;function J(){if(!I){I=true;var a=m.createElement(xb);a.src=yb;a.id=Q;a.style.cssText=zb;a.tabIndex=-1;m.body.appendChild(a);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Ab});a.contentWindow.location.replace(s+L)}}
v[Bb]=function(){var b=null;var c=Cb;try{if(!b){var d=location.search;var e=d.indexOf(Db);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(Eb,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){b=F(Bb)}if(!b){b=l[Fb]}if(b){c=b}while(b&&!E(Bb,b)){var h=b.lastIndexOf(Gb);if(h<0){b=null;break}b=b.substring(0,h)}}catch(a){alert(Hb+a)}l[Fb]=c;return b||Cb};u[Bb]={de:0,'default':1,en:2};serendipity.onScriptLoad=function(){if(I){q=true;B()}};serendipity.onInjectionDone=function(){p=true;n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:Ib,millis:(new Date).getTime(),type:Y});B()};D();C();var K;var L;if(A()){if(l.external&&(l.external.initModule&&l.external.initModule(Q))){l.location.reload();return}L=Jb;K=P}n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Kb});if(!A()){try{G([Lb],Mb);G([Nb],Ob);G([Cb],Pb);K=w[H(Bb)];var M=K.indexOf(Qb);if(M!=-1){x=Number(K.substring(M+1));K=K.substring(0,M)}L=K+Rb}catch(a){return}}var N;function O(){if(!r){r=true;if(!__gwt_stylesLoaded[Sb]){var a=m.createElement(Tb);__gwt_stylesLoaded[Sb]=a;a.setAttribute(Ub,Vb);a.setAttribute(Wb,s+Sb);m.getElementsByTagName(Xb)[0].appendChild(a)}B();if(m.removeEventListener){m.removeEventListener(Yb,O,false)}if(N){clearInterval(N)}}}
if(m.addEventListener){m.addEventListener(Yb,function(){J();O()},false)}var N=setInterval(function(){if(/loaded|complete/.test(m.readyState)){J();O()}},50);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Y});n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:Ib,millis:(new Date).getTime(),type:T});if(!__gwt_scriptsLoaded[Zb]){__gwt_scriptsLoaded[Zb]=true;document.write($b+s+_b)}if(!__gwt_scriptsLoaded[ac]){__gwt_scriptsLoaded[ac]=true;document.write($b+s+bc)}if(!__gwt_scriptsLoaded[cc]){__gwt_scriptsLoaded[cc]=true;document.write($b+s+dc)}if(!__gwt_scriptsLoaded[ec]){__gwt_scriptsLoaded[ec]=true;document.write($b+s+fc)}if(!__gwt_scriptsLoaded[gc]){__gwt_scriptsLoaded[gc]=true;document.write($b+s+hc)}if(!__gwt_scriptsLoaded[ic]){__gwt_scriptsLoaded[ic]=true;document.write($b+s+jc)}if(!__gwt_scriptsLoaded[kc]){__gwt_scriptsLoaded[kc]=true;document.write($b+s+lc)}if(!__gwt_scriptsLoaded[mc]){__gwt_scriptsLoaded[mc]=true;document.write($b+s+nc)}if(!__gwt_scriptsLoaded[oc]){__gwt_scriptsLoaded[oc]=true;document.write($b+s+pc)}if(!__gwt_scriptsLoaded[qc]){__gwt_scriptsLoaded[qc]=true;document.write($b+s+rc)}if(!__gwt_scriptsLoaded[sc]){__gwt_scriptsLoaded[sc]=true;document.write($b+s+tc)}if(!__gwt_scriptsLoaded[uc]){__gwt_scriptsLoaded[uc]=true;document.write($b+s+vc)}if(!__gwt_scriptsLoaded[wc]){__gwt_scriptsLoaded[wc]=true;document.write($b+s+xc)}m.write(yc)}
serendipity();